//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnapSack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Paniers = new HashSet<Panier>();
            this.Sacs = new HashSet<Sac>();
            this.Joueurs = new HashSet<Joueur>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int idItem { get; set; }
        public string nom { get; set; }
        public short idType { get; set; }
        public decimal prix { get; set; }
        public decimal poid { get; set; }
        public string urlImage { get; set; }
        public int qte { get; set; }
        public Nullable<bool> disponibilite { get; set; }
        public string description { get; set; }
        public Nullable<int> TypesArme_idType { get; set; }
    
        public virtual Arme Arme { get; set; }
        public virtual Armure Armure { get; set; }
        public virtual TypesItem TypesItem { get; set; }
        public virtual Medicament Medicament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Panier> Paniers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sac> Sacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Joueur> Joueurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
