//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnapSack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Joueur()
        {
            this.Ratings = new HashSet<Rating>();
            this.Items = new HashSet<Item>();
        }
    
        public int idJoueur { get; set; }
        public byte[] password { get; set; }
        public string alias { get; set; }
        public int dexterite { get; set; }
        public int poidMaximale { get; set; }
        public decimal montantCaps { get; set; }
        public bool isAdmin { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public decimal remainGiveAdmin { get; set; }
    
        public virtual Panier Panier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual Sac Sac { get; set; }
        public virtual Transaction Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
