//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnapSack.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnapSackDbEntities : DbContext
    {
        public KnapSackDbEntities()
            : base("name=KnapSackDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arme> Armes { get; set; }
        public virtual DbSet<Armure> Armures { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Joueur> Joueurs { get; set; }
        public virtual DbSet<Medicament> Medicaments { get; set; }
        public virtual DbSet<Panier> Paniers { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Sac> Sacs { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TypesArme> TypesArmes { get; set; }
        public virtual DbSet<TypesItem> TypesItems { get; set; }
    }
}
