//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnapSack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int idJoueur { get; set; }
        public int rating { get; set; }
        public int idItem { get; set; }
        public string commentaire { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Joueur Joueur { get; set; }
    }
}
